export const ADD_CITY = 'ADD_CITY';
export const ADD_LOCATION = 'ADD_LOCATION';
export const FETCH_CITIES = 'FETCH_CITIES';
export const FETCH_CITIES_SUCCESS = 'FETCH_CITIES_SUCCESS';
export const FETCH_CITIES_FAILURE = 'FETCH_CITIES_FAILURE';
